### ISSUE TITLE
test_catalog.FullCopyTest.test_full_copy_4 fails locally for me

### ISSUE THREAD

**Issue by schwehr** [stac-utils/pystac#196]
Wondering if I have something funky in my environment.  This is on a debian-testing variant os.

```
python3 --version
Python 3.8.5

pip install .
python -m unittest discover tests -v
[SNIP]
test_full_copy_4 (test_catalog.FullCopyTest) ... FAIL
[SNIP]
======================================================================
FAIL: test_full_copy_4 (test_catalog.FullCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/schwehr/src/pystac-schwehr/tests/test_catalog.py", line 669, in test_full_copy_4
    self.assertTrue(os.path.exists(href))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 161 tests in 25.829s
```

Then adding

and running

```
python -m unittest discover tests -v -k test_catalog.FullCopyTest.test_full_copy_4
test_full_copy_4 (test_catalog.FullCopyTest) ... FAIL

======================================================================
FAIL: test_full_copy_4 (test_catalog.FullCopyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/schwehr/src/pystac-schwehr/tests/test_catalog.py", line 669, in test_full_copy_4
    self.assertTrue(os.path.exists(href), href)
AssertionError: False is not true : ../../../../../../usr/local/google/home/schwehr/src/pystac-schwehr/tests/data-files/catalogs/test-case-2/1a8c1632-fa91-4a62-b33e-3a87c2ebdf16/5b922d42-9a77-4f79-a672-86096f7f849e/cf73ec1a-d790-4b59-b077-e101738571ed/data.geojson
```

Looking for the file, it's not there:
```
ls -l ../../../../../../usr/local/google/home/schwehr/src/pystac-schwehr/tests/data-files/catalogs/test-case-2/1a8c1632-fa91-4a62-b33e-3a87c2ebdf16/5b922d42-9a77-4f79-a672-86096f7f849e/cf73ec1a-d790-4b59-b077-e101738571ed/data.geojson
ls: cannot access '../../../../../../usr/local/google/home/schwehr/src/pystac-schwehr/tests/data-files/catalogs/test-case-2/1a8c1632-fa91-4a62-b33e-3a87c2ebdf16/5b922d42-9a77-4f79-a672-86096f7f849e/cf73ec1a-d790-4b59-b077-e101738571ed/data.geojson': No such file or directory
```

It looks like it is somehow missing a `../`.  Adding one, finds the file:

```
ls -l ../../../../../../../usr/local/google/home/schwehr/src/pystac-schwehr/tests/data-files/catalogs/test-case-2/1a8c1632-fa91-4a62-b33e-3a87c2ebdf16/5b922d42-9a77-4f79-a672-86096f7f849e/cf73ec1a-d790-4b59-b077-e101738571ed/data.geojson
-rw-r----- 1 schwehr primarygroup 1886 Aug 18 09:45 ../../../../../../../usr/local/google/home/schwehr/src/pystac-schwehr/tests/data-files/catalogs/test-case-2/1a8c1632-fa91-4a62-b33e-3a87c2ebdf16/5b922d42-9a77-4f79-a672-86096f7f849e/cf73ec1a-d790-4b59-b077-e101738571ed/data.geojson
```

**Comment by lossyrob** [comment]
Can you try this again with the most recent develop? I have a suspicion that this is related to the relative asset HREF bug that was recently fixed.

**Comment by schwehr** [comment]
Awesome!

```
python3 -m unittest discover tests
.........................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 249 tests in 35.716s

OK
