### ISSUE TITLE
v0.2/projjson.schema.json is missing

### ISSUE THREAD

**Issue by schwehr** [stac-utils/pystac#237]
Having some way to make a cache/snapshot of the schemas would be really nice.  In addition to helping when resources drop of the internet, anyone testing in a locked down environment (e.g. Google's "forge") will then be able to do validations.  Also, folks in the far future have a chance of repeatability with older versions of STAC.

https://github.com/OSGeo/PROJ/issues/2408

Also, the error message here is not the best with `KeyError` and a URL.

From develop head:

```
python3 -m unittest discover tests -v -k  test_validate_examples
test_validate_examples (validation.test_validate.ValidateTest) ... 
======================================================================
ERROR: test_validate_examples (validation.test_validate.ValidateTest) [/usr/local/google/home/schwehr/src/pystac/tests/data-files/examples/1.0.0-beta.2/extensions/projection/examples/example-landsat8.json]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 774, in resolve_from_url
    document = self.store[url]
  File "/usr/lib/python3/dist-packages/jsonschema/_utils.py", line 22, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: 'https://proj.org/schemas/v0.2/projjson.schema.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 777, in resolve_from_url
    document = self.resolve_remote(url)
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 860, in resolve_remote
    result = requests.get(uri).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/schwehr/src/pystac/tests/validation/test_validate.py", line 55, in test_validate_examples
    pystac.validation.validate_dict(stac_json)
  File "/usr/local/google/home/schwehr/src/pystac/pystac/validation/__init__.py", line 87, in validate_dict
    return RegisteredValidator.get_validator().validate(stac_dict, stac_object_type, stac_version,
  File "/usr/local/google/home/schwehr/src/pystac/pystac/validation/stac_validator.py", line 80, in validate
    ext_result = self.validate_extension(json_dict, stac_object_type, stac_version,
  File "/usr/local/google/home/schwehr/src/pystac/pystac/validation/stac_validator.py", line 201, in validate_extension
    self._validate_from_uri(stac_dict, schema_uri)
  File "/usr/local/google/home/schwehr/src/pystac/pystac/validation/stac_validator.py", line 130, in _validate_from_uri
    jsonschema.validate(instance=stac_dict, schema=schema, resolver=resolver)
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 932, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
  File "/usr/lib/python3/dist-packages/jsonschema/exceptions.py", line 367, in best_match
    best = next(errors, None)
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/lib/python3/dist-packages/jsonschema/_validators.py", line 315, in allOf
    for error in validator.descend(instance, subschema, schema_path=index):
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/lib/python3/dist-packages/jsonschema/_validators.py", line 263, in ref
    for error in validator.descend(instance, resolved):
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/lib/python3/dist-packages/jsonschema/_validators.py", line 282, in properties
    for error in validator.descend(
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/lib/python3/dist-packages/jsonschema/_validators.py", line 282, in properties
    for error in validator.descend(
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/lib/python3/dist-packages/jsonschema/_validators.py", line 337, in oneOf
    errs = list(validator.descend(instance, subschema, schema_path=index))
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/usr/lib/python3/dist-packages/jsonschema/_validators.py", line 259, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 766, in resolve
    return url, self._remote_cache(url)
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 779, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 1 test in 6.919s

FAILED (errors=1)
```

**Comment by schwehr** [comment]
https://github.com/OSGeo/PROJ/pull/2409 fixed the missing https://proj.org/schemas/v0.2/projjson.schema.json, but it still leaves the point about pystac being brittle w.r.t. external schemas and not repeatable in the future when old schemas are removed from their current home.

**Comment by lossyrob** [comment]
PySTAC does leave a door open to an alternate set of schemas - the [SchemaUriMap](https://github.com/stac-utils/pystac/blob/develop/pystac/validation/schema_uri_map.py#L8) defines the interface of how stac objects and extensions etc are mapped to URIs, and the [DefaultSchemaUriMap](https://github.com/stac-utils/pystac/blob/develop/pystac/validation/schema_uri_map.py#L42) is the one that maps it to all the online-hosted schemas. You could create another implementation, and then set the pystac validator using [pystac.validator.set_validator](https://github.com/stac-utils/pystac/blob/develop/pystac/validation/__init__.py#L156) as a JsonSchemaSTACValidator instantiated with your custom schema map.

The issue you experienced isn't directly with a hosted STAC schema, but one referenced inside the projection extension schema. So this means if you wanted to host your own, you'd have to also cache all the transient schemas and modify any schema definitions to point to your cached version.

Snapshotting schemas seems like a particular use case and complicated (particularly due to the transitive schemas), so I'm not sure a more robust solution is needed here. Do you think the above mentioned mechanism would work for your use case?

**Comment by schwehr** [comment]
Yeah, no worries about closing.
