### ISSUE TITLE
Fix Sphinx LateX build

### ISSUE THREAD

**Issue by duckontheweb** [stac-utils/pystac#552]
#551 Broke the LateX Sphinx build, the issue appears to be happening somewhere in `nbsphinx`. In fixing this we should probably also use a `.readthedocs.yml` file for configuration instead of configuring things through the ReadTheDocs admin UI to make the configuration more transparent

From the ReadTheDocs logs for the [failed build](https://readthedocs.org/projects/pystac/builds/14221795/):

```
Running Sphinx v4.1.0
loading translations [en]... done
making output directory... done
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing pystac.tex... index quickstart concepts api tutorials contributing 
resolving references...
done
writing... failed

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystac/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 2151, in depart_codearea_latex
    assert 'Verbatim' in lines[0]
AssertionError
The full traceback has been saved in /tmp/sphinx-err-gepoe3b9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Here's a more thorough traceback from a local run:

```
Traceback (most recent call last):
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 290, in build_update
    self.build(['__all__'], to_build)
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 357, in build
    self.write(docnames, list(updated_docnames), method)
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/sphinx/builders/latex/__init__.py", line 308, in write
    docwriter.write(doctree, destination)
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/sphinx/writers/latex.py", line 99, in translate
    self.document.walkabout(visitor)
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 5 more times]
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/docutils/nodes.py", line 240, in walkabout
    visitor.dispatch_departure(self)
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/sphinx/util/docutils.py", line 486, in dispatch_departure
    method(node)
  File "/Users/jduckworth/.pyenv/versions/3.8.9/envs/pystac-dev/lib/python3.8/site-packages/nbsphinx.py", line 2151, in depart_codearea_latex
    assert 'Verbatim' in lines[0]
AssertionError
```

**Comment by duckontheweb** [comment]
Closed via #553
